name: Polly Beta Audio on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  run-polly-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install boto3
        run: pip install boto3

      - name: Run synthesize script for beta
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: green-bucket-s3-feb
          S3_KEY: polly-audio/beta.mp3
        run: python synthesize.py
